#!/usr/bin/env bash
# 101-manage_my_process

SCRIPT="./manage_my_process"
PID_FILE="/var/run/my_process.pid"

case $1 in
    start)
        if [ -e "$PID_FILE" ]; then
            echo "manage_my_process is already running."
        else
            $SCRIPT &
            echo $! > $PID_FILE
            echo "manage_my_process started"
        fi
        ;;
    stop)
        if [ -e "$PID_FILE" ]; then
            kill -TERM $(cat $PID_FILE)
            rm $PID_FILE
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running."
        fi
        ;;
    restart)
        if [ -e "$PID_FILE" ]; then
            kill -TERM $(cat $PID_FILE)
            rm $PID_FILE
        fi
        $SCRIPT &
        echo $! > $PID_FILE
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac

